import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import AuthProvider from '@/provider/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className='min-h-screen bg-gray-900 text-white'>
            <div className='max-w-[1536px] mr-auto ml-auto pl-20 pr-20 2xl:max-w-[1366px] xl:max-w-[1024px] lg:max-w-[768px] lg:pl-10 lg:pr-10 md:max-w-[640px] sm:max-w-[475px]'>
              <Navbar />
              {children}
              <Footer />
            </div>
          </div>

        </AuthProvider>
      </body>
    </html>
  )
}
